[project]
name = "sensor-fusion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.3.4",
    "pyyaml>=6.0.2",
    "ruff>=0.9.7",
]

[tool.ruff]
src = ["src", "tests"]
